version: '3'
services:
  todo-list_app:
    container_name: todo-list_app
    image: todo-list_app:1.0
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
  
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
